# Generated by Django 4.2.3 on 2023-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('date', models.DateField()),
                ('emotion', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('content', models.TextField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
