# Generated by Django 4.2.3 on 2023-07-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biographyitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(null=True)),
            ],
        ),
    ]
