# Generated by Django 4.2.3 on 2023-07-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayou', '0002_biographyitem_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='biographyitem',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
